version: 2.1
jobs:
  my-job:
      docker:
        - image: circleci/node:latest
      steps:
      - checkout
      - run:
          name: "Build"
          command: npm install
      - run:
          name: "Test the image..."
          command: npm run coverage
workflows:
  my-job-workflow:
    jobs:
      - my-job